export TEACHER_CHECKPOINT=/path/to/checkpoint/
export OUTPUT_DIR=gs://arabert-mobilebert/mobilebert-30K
export DATA=DATA=gs://arabert-mobilebert/**/tf_examples.tfrecord*
python3 run_pretraining.py \
  --attention_distill_factor=1 \
  --bert_config_file=config/uncased_L-24_H-128_B-512_A-4_F-4_OPT.json \
  --bert_teacher_config_file=config/ibert.json \
  --beta_distill_factor=5000 \
  --distill_ground_truth_ratio=0.5 \
  --distill_temperature=1 \
  --do_train \
  --first_input_file=${DATA} \
  --first_max_seq_length=128 \
  --first_num_train_steps=0 \
  --first_train_batch_size=256 \
  --gamma_distill_factor=5 \
  --hidden_distill_factor=100 \
  --init_checkpoint=gs://arabert-mobilebert/ibert-forth/model.ckpt-1000 \
  --input_file=${DATA} \
  --layer_wise_warmup \
  --learning_rate=0.0015 \
  --max_predictions_per_seq=20 \
  --max_seq_length=512 \
  --num_distill_steps=240000 \
  --num_train_steps=2000000 \
  --num_warmup_steps=10000 \
  --optimizer=lamb \
  --output_dir=${OUTPUT_DIR} \
  --save_checkpoints_steps=10000 \
  --train_batch_size=256 \
  --use_einsum \
  --use_summary \
  --use_tpu \
  --tpu_name=${TPU_NAME} \
